# Generated by Django 2.0.7 on 2018-07-20 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_auto_20180720_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='parent_store',
        ),
        migrations.AlterField(
            model_name='item',
            name='zone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='shoplist',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='life.Item'),
        ),
        migrations.AlterField(
            model_name='store',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='life.Item'),
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
