# Generated by Django 2.0.7 on 2018-07-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0004_auto_20180720_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stores',
            field=models.ManyToManyField(to='life.Store'),
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='items',
        ),
        migrations.AddField(
            model_name='shoplist',
            name='items',
            field=models.ManyToManyField(to='life.Item'),
        ),
        migrations.RemoveField(
            model_name='store',
            name='inventory',
        ),
        migrations.AddField(
            model_name='store',
            name='inventory',
            field=models.ManyToManyField(to='life.Item'),
        ),
    ]
