# Generated by Django 2.0.7 on 2018-07-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0005_auto_20180720_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='stores',
        ),
        migrations.AddField(
            model_name='shoplist',
            name='name',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoplist',
            name='items',
            field=models.ManyToManyField(related_name='_shoplist_items_+', to='life.Item'),
        ),
    ]
