# Generated by Django 2.0.7 on 2018-07-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0006_auto_20180721_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoplist',
            name='items',
        ),
        migrations.AddField(
            model_name='shoplist',
            name='contents',
            field=models.ManyToManyField(related_name='_shoplist_contents_+', to='life.Item'),
        ),
    ]
